-- MySQL Script generated by MySQL Workbench
-- 04/25/17 11:30:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Age` INT UNSIGNED NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eleves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eleves` (
  `id_utilisateur` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Numero_eleve` INT UNSIGNED NOT NULL,
  `Annee` INT UNSIGNED NOT NULL,
  `Specialite` VARCHAR(45) NULL,
  UNIQUE INDEX `id_utilisateur_UNIQUE` (`id_utilisateur` ASC),
  UNIQUE INDEX `Numero eleve_UNIQUE` (`Numero_eleve` ASC),
  PRIMARY KEY (`id_utilisateur`),
  CONSTRAINT `Eleves_idUtil`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grille_de_competence_APP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grille_de_competence_APP` (
  `id_grille` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom_grille` VARCHAR(45) NOT NULL,
  `Annee` VARCHAR(4) NOT NULL,
  `Date` INT NOT NULL,
  PRIMARY KEY (`id_grille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Groupe` (
  `id_groupe` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_groupe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Planning` (
  `id_planning` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom_planning` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_planning`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Competence_principale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competence_principale` (
  `id_comp` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom_competence_principale` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_comp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Competence_Secondaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competence_Secondaire` (
  `id_comp_second` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_comp_second`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Competence_secondaire_utilise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competence_secondaire_utilise` (
  `id_comp_second_util` INT UNSIGNED NOT NULL,
  `id_comp_second` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_comp_second_util`),
  INDEX `CompSecUtil_CompSec_idx` (`id_comp_second` ASC),
  CONSTRAINT `CompSecUtil_CompSec`
    FOREIGN KEY (`id_comp_second`)
    REFERENCES `mydb`.`Competence_Secondaire` (`id_comp_second`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Critere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Critere` (
  `id_critere` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descriptif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_critere`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appartient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appartient` (
  `idEleve` INT UNSIGNED NOT NULL,
  `idGroupe` INT UNSIGNED NOT NULL,
  INDEX `Appartient_Eleves_idx` (`idEleve` ASC),
  INDEX `Appartient_Groupe_idx` (`idGroupe` ASC),
  CONSTRAINT `Appartient_Eleves`
    FOREIGN KEY (`idEleve`)
    REFERENCES `mydb`.`Eleves` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Appartient_Groupe`
    FOREIGN KEY (`idGroupe`)
    REFERENCES `mydb`.`Groupe` (`id_groupe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lie` (
  `idEleves` INT UNSIGNED NOT NULL,
  `idGroupe` INT UNSIGNED NOT NULL,
  `idStatus` INT UNSIGNED NOT NULL,
  INDEX `Lie_eleves_idx` (`idEleves` ASC),
  INDEX `Lie_groupe_idx` (`idGroupe` ASC),
  INDEX `Lie_status_idx` (`idStatus` ASC),
  CONSTRAINT `Lie_eleves`
    FOREIGN KEY (`idEleves`)
    REFERENCES `mydb`.`Eleves` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Lie_groupe`
    FOREIGN KEY (`idGroupe`)
    REFERENCES `mydb`.`Groupe` (`id_groupe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Lie_status`
    FOREIGN KEY (`idStatus`)
    REFERENCES `mydb`.`Status` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evalue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evalue` (
  `idEleve` INT UNSIGNED NOT NULL,
  `idGroupe` INT UNSIGNED NOT NULL,
  `idComp_Sec_Util` INT UNSIGNED NOT NULL,
  `Evaluation` VARCHAR(45) NOT NULL,
  `CommentaireIndividuel` TEXT(1000) NOT NULL,
  `CommentaireGroupe` TEXT(1000) NOT NULL,
  `CommentaireProfesseur` TEXT(1000) NOT NULL,
  INDEX `Evalue_Eleve_idx` (`idEleve` ASC),
  INDEX `Evalue_Groupe_idx` (`idGroupe` ASC),
  INDEX `Evalue_CompSecUtil_idx` (`idComp_Sec_Util` ASC),
  CONSTRAINT `Evalue_Eleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `mydb`.`Eleves` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Evalue_Groupe`
    FOREIGN KEY (`idGroupe`)
    REFERENCES `mydb`.`Groupe` (`id_groupe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Evalue_CompSecUtil`
    FOREIGN KEY (`idComp_Sec_Util`)
    REFERENCES `mydb`.`Competence_secondaire_utilise` (`id_comp_second_util`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulte` (
  `Evaluation` VARCHAR(45) NOT NULL,
  `CommentaireGroupe` TEXT(1000) NOT NULL,
  `CommentaireIndividuel` TEXT(1000) NOT NULL,
  `idEleve` INT UNSIGNED NOT NULL,
  `idCom_Sec_Util` INT UNSIGNED NOT NULL,
  INDEX `Consulte_Eleve_idx` (`idEleve` ASC),
  INDEX `Consulte_CompSecUtil_idx` (`idCom_Sec_Util` ASC),
  CONSTRAINT `Consulte_Eleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `mydb`.`Eleves` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Consulte_CompSecUtil`
    FOREIGN KEY (`idCom_Sec_Util`)
    REFERENCES `mydb`.`Competence_secondaire_utilise` (`id_comp_second_util`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lie2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lie2` (
  `idEleve` INT UNSIGNED NOT NULL,
  `idGrilleComp` INT UNSIGNED NOT NULL,
  INDEX `Lie2_Eleve_idx` (`idEleve` ASC),
  INDEX `Lie2_GrilleComp_idx` (`idGrilleComp` ASC),
  CONSTRAINT `Lie2_Eleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `mydb`.`Eleves` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Lie2_GrilleComp`
    FOREIGN KEY (`idGrilleComp`)
    REFERENCES `mydb`.`Grille_de_competence_APP` (`id_grille`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lie3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lie3` (
  `idGrilleComp` INT UNSIGNED NOT NULL,
  `idCompPrin` INT UNSIGNED NOT NULL,
  INDEX `Lie3_GrilleComp_idx` (`idGrilleComp` ASC),
  INDEX `Lie3_CompPrin_idx` (`idCompPrin` ASC),
  CONSTRAINT `Lie3_GrilleComp`
    FOREIGN KEY (`idGrilleComp`)
    REFERENCES `mydb`.`Grille_de_competence_APP` (`id_grille`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Lie3_CompPrin`
    FOREIGN KEY (`idCompPrin`)
    REFERENCES `mydb`.`Competence_principale` (`id_comp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lie4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lie4` (
  `idCompPrin` INT UNSIGNED NOT NULL,
  `idCompSecUtil` INT UNSIGNED NOT NULL,
  INDEX `Lie4_idCompPrin_idx` (`idCompPrin` ASC),
  INDEX `Lie4_idCompSecUtil_idx` (`idCompSecUtil` ASC),
  CONSTRAINT `Lie4_idCompPrin`
    FOREIGN KEY (`idCompPrin`)
    REFERENCES `mydb`.`Competence_principale` (`id_comp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Lie4_idCompSecUtil`
    FOREIGN KEY (`idCompSecUtil`)
    REFERENCES `mydb`.`Competence_secondaire_utilise` (`id_comp_second_util`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lie5`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lie5` (
  `idCompSecUtil` INT UNSIGNED NOT NULL,
  `idCritere` INT UNSIGNED NOT NULL,
  INDEX `Lie5_CompSecUtil_idx` (`idCompSecUtil` ASC),
  INDEX `Lie5_Critere_idx` (`idCritere` ASC),
  CONSTRAINT `Lie5_CompSecUtil`
    FOREIGN KEY (`idCompSecUtil`)
    REFERENCES `mydb`.`Competence_secondaire_utilise` (`id_comp_second_util`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Lie5_Critere`
    FOREIGN KEY (`idCritere`)
    REFERENCES `mydb`.`Critere` (`id_critere`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lie6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lie6` (
  `idGroupe` INT UNSIGNED NOT NULL,
  `idPlaning` INT UNSIGNED NOT NULL,
  `Descriptif` TEXT(1000) NOT NULL,
  `Date` DATE NOT NULL,
  `Heure` TIME NULL,
  INDEX `Lie6_Groupe_idx` (`idGroupe` ASC),
  INDEX `Lie6_Planning_idx` (`idPlaning` ASC),
  CONSTRAINT `Lie6_Groupe`
    FOREIGN KEY (`idGroupe`)
    REFERENCES `mydb`.`Groupe` (`id_groupe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Lie6_Planning`
    FOREIGN KEY (`idPlaning`)
    REFERENCES `mydb`.`Planning` (`id_planning`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
